import { cookies } from "next/headers";
import { createAdminClient } from "@/lib/supabase/admin";
import { shippo, businessAddress } from "@/lib/shippo";

export async function POST(
  _req: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const jar = await cookies();
  if (jar.get("admin_auth")?.value !== process.env.ADMIN_PASSWORD) {
    return Response.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;
  const admin = createAdminClient();

  const { data: order } = await admin
    .from("orders")
    .select("id, ship_from_address, inbound_method, customer_email, customer_name, customer_phone")
    .eq("id", id)
    .single();

  if (!order) return Response.json({ error: "Order not found" }, { status: 404 });
  if (order.inbound_method !== "buy_label") {
    return Response.json({ error: "This order does not use a prepaid label" }, { status: 400 });
  }

  const addr = order.ship_from_address as Record<string, string> | null;
  if (!addr?.street1 || !addr?.city || !addr?.zip) {
    return Response.json({ error: `Missing address fields — street1: "${addr?.street1}", city: "${addr?.city}", zip: "${addr?.zip}"` }, { status: 400 });
  }

  // Create Shippo shipment using SDK + the same businessAddress used everywhere else
  let shipment: Awaited<ReturnType<typeof shippo.shipments.create>>;
  try {
    shipment = await shippo.shipments.create({
      addressFrom: {
        name: addr.name ?? (order.customer_name as string) ?? "Customer",
        street1: addr.street1,
        street2: addr.street2 ?? "",
        city: addr.city,
        state: addr.state ?? "",
        zip: addr.zip,
        country: addr.country ?? "US",
        phone: addr.phone ?? (order.customer_phone as string) ?? "",
        email: (order.customer_email as string) ?? "",
      },
      addressTo: {
        name: businessAddress.name,
        street1: businessAddress.street1,
        street2: businessAddress.street2 ?? "",
        city: businessAddress.city,
        state: businessAddress.state,
        zip: businessAddress.zip,
        country: businessAddress.country ?? "US",
        phone: businessAddress.phone,
        email: businessAddress.email,
      },
      parcels: [{
        length: "12", width: "9", height: "2",
        distanceUnit: "in",
        weight: "1", massUnit: "lb",
      }],
      async: false,
    });
  } catch (e) {
    return Response.json({ error: `Shippo shipment error: ${e instanceof Error ? e.message : String(e)}` }, { status: 502 });
  }

  const rates = (shipment.rates ?? []).filter((r) => r.objectId && r.amount);
  if (!rates.length) {
    return Response.json({
      error: `No rates returned. Address validation messages: ${JSON.stringify((shipment as Record<string, unknown>).messages ?? "none").slice(0, 400)}`,
    }, { status: 502 });
  }

  // Prefer USPS, then pick cheapest
  const usps = rates.filter((r) => r.provider?.toUpperCase().includes("USPS"));
  const pool = usps.length > 0 ? usps : rates;
  const cheapest = [...pool].sort((a, b) => parseFloat(a.amount) - parseFloat(b.amount))[0];

  // Purchase label via REST API (SDK strips `extra` fields needed for insurance/signature)
  const token = process.env.SHIPPO_API_TOKEN!;
  let tx: Record<string, unknown>;
  try {
    const txRes = await fetch("https://api.goshippo.com/transactions/", {
      method: "POST",
      headers: { Authorization: `ShippoToken ${token}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        rate: cheapest.objectId,
        label_file_type: "PDF_4x6",
        async: false,
      }),
    });
    tx = await txRes.json();
  } catch (e) {
    return Response.json({ error: `Shippo transaction error: ${e instanceof Error ? e.message : String(e)}` }, { status: 502 });
  }

  if (tx.status !== "SUCCESS" || !tx.label_url) {
    return Response.json({
      error: `Shippo transaction failed (status: ${tx.status}). Details: ${JSON.stringify(tx.messages ?? tx).slice(0, 400)}`,
    }, { status: 502 });
  }

  const labelUrl = tx.label_url as string;
  const trackingNumber = (tx.tracking_number as string) ?? null;

  await admin
    .from("orders")
    .update({
      shipping_label_url: labelUrl,
      ...(trackingNumber ? { inbound_tracking_number: trackingNumber } : {}),
    })
    .eq("id", id);

  await admin.from("order_events").insert({
    order_id: id,
    event_type: "label_regenerated",
    description: `Inbound label regenerated by admin. Carrier: ${cheapest.provider}. Rate: $${cheapest.amount}. Tracking: ${trackingNumber ?? "N/A"}`,
    is_customer_visible: false,
  });

  return Response.json({ ok: true, labelUrl, trackingNumber });
}
